import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins, Roboto } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import { QueryClientProvider } from "@tanstack/react-query";
import queryClient from "@/lib/queryClient";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ['100', '300', '400', '500']
})

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ['100', '300', '400', '500']
})
export const metadata: Metadata = {
  title: "Astro",
  description: "Generated by create next app",
  icons: {
    icon: 'logo.svg'
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${roboto.className} ${poppins.variable} antialiased`}
      >
        <QueryClientProvider client={queryClient}>
        <Toaster position="top-center" richColors/>
        {children}
        </QueryClientProvider>
      </body>
    </html>
  );
}
